"""Utility modules for ab-cli."""

from ab_cli.utils.logging import (
    log_info,
    log_success,
    log_warning,
    log_error,
    log_debug,
    RED,
    GREEN,
    YELLOW,
    BLUE,
    CYAN,
    NC,
)
from ab_cli.utils.exceptions import (
    AbCliError,
    GitError,
    LLMError,
    ConfigError,
    FileOperationError,
)
from ab_cli.utils.git_helpers import (
    run_git,
    is_git_repo,
    require_git_repo,
    get_repo_root,
    get_current_branch,
    is_protected_branch,
    branch_exists,
    create_branch,
    get_staged_files,
    get_unstaged_files,
    get_untracked_files,
    get_staged_diff,
    get_staged_name_status,
    stage_all_files,
    has_uncommitted_changes,
    create_commit,
    get_latest_commit,
    get_recent_commits,
    get_commit_message,
    get_commit_subject,
    get_short_hash,
    is_merge_commit,
    get_commit_diff,
    get_commit_files,
    list_commits,
    has_remotes,
    check_commits_pushed,
    get_latest_tag,
    get_all_tags,
    get_conflicted_files,
    detect_base_branch,
    get_commits_ahead,
    get_diff_against_base,
    get_commits_log,
    get_files_changed,
)
from ab_cli.utils.api import (
    send_to_openrouter,
    build_specialist_prefix,
    set_verbose as set_api_verbose,
)
from ab_cli.utils.llm_helpers import (
    call_llm,
    call_llm_with_model_info,
    get_llm_text,
)
from ab_cli.utils.prompt_builder import (
    build_generation_prompt,
    clean_llm_response,
    normalize_identifier,
    strip_markdown_code_block,
)
from ab_cli.utils.error_handling import (
    cli_error_handler,
    handle_cli_errors,
)
from ab_cli.utils.file_processing import (
    is_binary_file,
    find_git_root,
    find_aiignore_files,
    load_aiignore_spec,
    should_ignore_path,
    process_file,
    estimate_file_tokens,
    get_directory_files,
)
from ab_cli.utils.history import (
    sanitize_sensitive_data,
    save_to_history,
    calculate_estimated_cost,
    update_history_index,
    cleanup_old_history,
)

__all__ = [
    # Logging functions
    'log_info',
    'log_success',
    'log_warning',
    'log_error',
    'log_debug',
    # Color constants
    'RED',
    'GREEN',
    'YELLOW',
    'BLUE',
    'CYAN',
    'NC',
    # Exceptions
    'AbCliError',
    'GitError',
    'LLMError',
    'ConfigError',
    'FileOperationError',
    # Git helpers
    'run_git',
    'is_git_repo',
    'require_git_repo',
    'get_repo_root',
    'get_current_branch',
    'is_protected_branch',
    'branch_exists',
    'create_branch',
    'get_staged_files',
    'get_unstaged_files',
    'get_untracked_files',
    'get_staged_diff',
    'get_staged_name_status',
    'stage_all_files',
    'has_uncommitted_changes',
    'create_commit',
    'get_latest_commit',
    'get_recent_commits',
    'get_commit_message',
    'get_commit_subject',
    'get_short_hash',
    'is_merge_commit',
    'get_commit_diff',
    'get_commit_files',
    'list_commits',
    'has_remotes',
    'check_commits_pushed',
    'get_latest_tag',
    'get_all_tags',
    'get_conflicted_files',
    'detect_base_branch',
    'get_commits_ahead',
    'get_diff_against_base',
    'get_commits_log',
    'get_files_changed',
    # API functions
    'send_to_openrouter',
    'build_specialist_prefix',
    'set_api_verbose',
    # LLM helpers
    'call_llm',
    'call_llm_with_model_info',
    'get_llm_text',
    # Error handling
    'cli_error_handler',
    'handle_cli_errors',
    # Prompt builder
    'build_generation_prompt',
    'clean_llm_response',
    'normalize_identifier',
    'strip_markdown_code_block',
    # File processing
    'is_binary_file',
    'find_git_root',
    'find_aiignore_files',
    'load_aiignore_spec',
    'should_ignore_path',
    'process_file',
    'estimate_file_tokens',
    'get_directory_files',
    # History
    'sanitize_sensitive_data',
    'save_to_history',
    'calculate_estimated_cost',
    'update_history_index',
    'cleanup_old_history',
]
